import { CourseFormData } from '../types/course';

export const SAMPLE_COURSES: CourseFormData[] = [
  {
    name: 'Programación I',
    day: 'Lunes',
    start_time: '08:00',
    end_time: '10:00',
    modality: 'Presencial',
    difficulty: 'Alta',
    credits: 4,
  },
  {
    name: 'Matemáticas Discretas',
    day: 'Martes',
    start_time: '10:00',
    end_time: '12:00',
    modality: 'Presencial',
    difficulty: 'Alta',
    credits: 4,
  },
  {
    name: 'Base de datos básica',
    day: 'Miércoles',
    start_time: '08:00',
    end_time: '10:00',
    modality: 'Virtual',
    difficulty: 'Media',
    credits: 3,
  },
  {
    name: 'Base de datos avanzada',
    day: 'Jueves',
    start_time: '10:00',
    end_time: '12:00',
    modality: 'Virtual',
    difficulty: 'Alta',
    credits: 4,
  },
  {
    name: 'Redes de Computadoras',
    day: 'Viernes',
    start_time: '08:00',
    end_time: '10:00',
    modality: 'Presencial',
    difficulty: 'Media',
    credits: 3,
  },
  {
    name: 'Sistemas Operativos',
    day: 'Lunes',
    start_time: '10:00',
    end_time: '12:00',
    modality: 'Virtual',
    difficulty: 'Alta',
    credits: 4,
  },
  {
    name: 'Inglés Técnico',
    day: 'Martes',
    start_time: '14:00',
    end_time: '16:00',
    modality: 'Virtual',
    difficulty: 'Baja',
    credits: 2,
  },
  {
    name: 'Ética Profesional',
    day: 'Miércoles',
    start_time: '14:00',
    end_time: '16:00',
    modality: 'Virtual',
    difficulty: 'Baja',
    credits: 2,
  },
];
